### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by bogdaniel** [Carbon-12/SCFusion#7]
Hello, i was wondering if you could provide a tutorial on how to compile it .. or provide a compiled version here on github because .. i'm not really good with C++

**Comment by Carbon-12** [comment]
I've been using Visual Studio to build it.  The project files are included with the source, so if you've got that all you should need to do is download & build wxWidgets (the current version uses wxWidgets v3.0.2), make sure you have the wxWidgets environment variables configured, and then you should be able to build SCFusion.

I've added compiled versions, but for the latest version you're better off checking SourceForge as I tend to add them there first: https://sourceforge.net/projects/scfusion/files/?source=navbar
